function save(){commit();localStorage.setItem('courtplay_v2',JSON.stringify(data));setStatus('Guardado en este iPad.');}saveBtn.addEventListener('click',save);
function wrapText(c,text,x,y,maxW,lineH,maxLines=3){const words=(text||'').split(/\s+/);let line='',lines=[];for(const w of words){const test=line?line+' '+w:w;if(c.measureText(test).width>maxW&&line){lines.push(line);line=w}else line=test}if(line)lines.push(line);lines.slice(0,maxLines).forEach((ln,i)=>c.fillText(ln,x,y+i*lineH));}
function compose(f,title,idx,total,out){const c=out.getContext('2d');c.fillStyle='#061c45';c.fillRect(0,0,out.width,out.height);c.fillStyle='#fff';c.font='800 38px system-ui';c.textAlign='left';c.fillText(title,52,58);c.fillStyle='#b9cae1';c.font='600 22px system-ui';c.textAlign='right';c.fillText(`Fase ${idx+1} / ${total}`,out.width-52,58);c.save();c.translate(70,100);c.scale(1.14,1.14);drawScene(f,c,{hideHandles:true});c.restore();c.fillStyle='#fff';c.globalAlpha=.07;c.fillRect(55,865,out.width-110,180);c.globalAlpha=1;c.fillStyle='#f47a20';c.font='800 22px system-ui';c.textAlign='left';c.fillText(`FASE ${idx+1}`,80,905);c.fillStyle='#fff';c.font='500 27px system-ui';wrapText(c,f.caption||'Sin explicación',80,950,out.width-160,36,3);}
pngBtn.addEventListener('click',()=>{commit();const out=document.createElement('canvas');out.width=1280;out.height=1080;compose(frame(),data.name,current,data.frames.length,out);const a=document.createElement('a');a.download=(data.name||'jugada').replace(/[^\w-]+/g,'_')+`_fase_${current+1}.png`;a.href=out.toDataURL('image/png');a.click();setStatus('PNG creado.');});
function interpFrame(a,b,t){const r=copy(a),map=new Map((b.players||[]).map(p=>[p.key,p]));r.players=(a.players||[]).map(p=>{const q=map.get(p.key)||p;return{...p,x:p.x+(q.x-p.x)*t,y:p.y+(q.y-p.y)*t}});r.ball={...a.ball,x:a.ball.x+(b.ball.x-a.ball.x)*t,y:a.ball.y+(b.ball.y-a.ball.y)*t};return r;}
async function animateCanvas(target,exportMode=false){if(playing&&!exportMode)return;const original=current;if(!exportMode){playing=true;playBtn.textContent='■ Detener'}for(let i=0;i<data.frames.length&& (exportMode||playing);i++){const a=data.frames[i],b=data.frames[Math.min(i+1,data.frames.length-1)],dur=(a.seconds||2.4)*1000,start=performance.now();while(performance.now()-start<dur&&(exportMode||playing)){const t=Math.min(1,(performance.now()-start)/dur),scene=i===data.frames.length-1?a:interpFrame(a,b,t);if(exportMode)target(scene,i);else{ctx.clearRect(0,0,W,H);drawScene(scene,ctx,{hideHandles:true});}await new Promise(requestAnimationFrame)}}if(!exportMode){playing=false;current=original;playBtn.textContent='▶ Animación';render();}}
playBtn.addEventListener('click',()=>{if(playing){playing=false;playBtn.textContent='▶ Animación'}else{commit();animateCanvas(null,false)}});
videoBtn.addEventListener('click',async()=>{commit();if(!window.MediaRecorder){setStatus('Este navegador no permite exportar video.');return}const out=document.createElement('canvas');out.width=1280;out.height=1080;if(!out.captureStream){setStatus('Safari no permite grabar el canvas en este dispositivo.');return}const types=['video/mp4;codecs=avc1.42E01E','video/mp4','video/webm;codecs=vp9','video/webm'],mime=types.find(x=>MediaRecorder.isTypeSupported?.(x))||'';let rec;try{rec=new MediaRecorder(out.captureStream(30),mime?{mimeType:mime,videoBitsPerSecond:6000000}:undefined)}catch(e){setStatus('No pude iniciar el exportador de video.');return}const chunks=[];rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};rec.onstop=()=>{const type=rec.mimeType||mime||'video/webm',ext=type.includes('mp4')?'mp4':'webm',blob=new Blob(chunks,{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(data.name||'jugada').replace(/[^\w-]+/g,'_')+'.'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);setStatus(`Video ${ext.toUpperCase()} creado.`)};rec.start(250);setStatus('Creando video…');await animateCanvas((scene,i)=>compose(scene,data.name,i,data.frames.length,out),true);rec.stop();});

if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
